### ISSUE TITLE
Debug build issue after Xamarin upgrade

### ISSUE THREAD

**Issue by ronpf** [jamesmontemagno/CurrentActivityPlugin#1]
## Bug

After upgrading to the latest stable channel Xamarin components yesterday (9/15/2016) I'm seeing the error below on app startup / crash. I was able to build/run successfully by unchecking the Android project option "Use Shared Mono Runtime". The same behavior can be seen with the sample project here: https://github.com/smstuebe/xamarin-fingerprint

[AndroidRuntime] java.lang.RuntimeException: Unable to instantiate application md5f216fcce3ac198002ccf3c84a44cc7b9.MainApplication: java.lang.ClassNotFoundException: Didn't find class "md5f216fcce3ac198002ccf3c84a44cc7b9.MainApplication" on path: DexPathList[[zip file "/data/app/com.hpsj.h2go.droid-1/base.apk"],nativeLibraryDirectories=[/data/app/com.hpsj.h2go.droid-1/lib/x86, /data/app/com.hpsj.h2go.droid-1/base.apk!/lib/x86, /vendor/lib, /system/lib]]
[AndroidRuntime]    at android.app.LoadedApk.makeApplication(LoadedApk.java:578)
[AndroidRuntime]    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4680)
[AndroidRuntime]    at android.app.ActivityThread.-wrap1(ActivityThread.java)
[AndroidRuntime]    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
[AndroidRuntime]    at android.os.Handler.dispatchMessage(Handler.java:102)
[AndroidRuntime]    at android.os.Looper.loop(Looper.java:148)
[AndroidRuntime]    at android.app.ActivityThread.main(ActivityThread.java:5417)
[AndroidRuntime]    at java.lang.reflect.Method.invoke(Native Method)
[AndroidRuntime]    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
[AndroidRuntime]    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
[AndroidRuntime] Caused by: java.lang.ClassNotFoundException: Didn't find class "md5f216fcce3ac198002ccf3c84a44cc7b9.MainApplication" on path: DexPathList[[zip file "/data/app/com.hpsj.h2go.droid-1/base.apk"],nativeLibraryDirectories=[/data/app/com.hpsj.h2go.droid-1/lib/x86, /data/app/com.hpsj.h2go.droid-1/base.apk!/lib/x86, /vendor/lib, /system/lib]]
[AndroidRuntime]    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
[AndroidRuntime]    at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
[AndroidRuntime]    at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
[AndroidRuntime]    at android.app.Instrumentation.newApplication(Instrumentation.java:981)
[AndroidRuntime]    at android.app.LoadedApk.makeApplication(LoadedApk.java:573)
[AndroidRuntime]    ... 9 more
[AndroidRuntime]    Suppressed: java.io.IOException: No original dex files found for dex location /data/app/com.hpsj.h2go.droid-1/base.apk
[AndroidRuntime]        at dalvik.system.DexFile.openDexFileNative(Native Method)
[AndroidRuntime]        at dalvik.system.DexFile.openDexFile(DexFile.java:295)
[AndroidRuntime]        at dalvik.system.DexFile.<init>(DexFile.java:80)
[AndroidRuntime]        at dalvik.system.DexFile.<init>(DexFile.java:59)
[AndroidRuntime]        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:279)
[AndroidRuntime]        at dalvik.system.DexPathList.makePathElements(DexPathList.java:248)
[AndroidRuntime]        at dalvik.system.DexPathList.<init>(DexPathList.java:120)
[AndroidRuntime]        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:48)
[AndroidRuntime]        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:65)
[AndroidRuntime]        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:58)
[AndroidRuntime]        at android.app.LoadedApk.getClassLoader(LoadedApk.java:376)
[AndroidRuntime]        at android.app.LoadedApk.makeApplication(LoadedApk.java:568)
[AndroidRuntime]        ... 9 more
[AndroidRuntime]    Suppressed: java.lang.ClassNotFoundException: md5f216fcce3ac198002ccf3c84a44cc7b9.MainApplication
[AndroidRuntime]        at java.lang.Class.classForName(Native Method)
[AndroidRuntime]        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
[AndroidRuntime]        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
[AndroidRuntime]        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
[AndroidRuntime]        ... 12 more
[AndroidRuntime]    Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

Version Number of Plugin: 1.0.1
Device Tested On:  Samsung Galaxy S5
Simulator Tested On: multiple
### Expected Behavior

No crash on startup
### Steps to reproduce the Behavior

Install and use the Plugin.CurrentActivity plugin with Plugin.Fingerprint.
Try debug build to sim or device
# System Info:

=== Xamarin Studio Enterprise ===

Version 6.1 (build 5441)
Installation UUID: []
Runtime:
    Mono 4.6.0 (mono-4.6.0-branch/746756c) (64-bit)
    GTK+ 2.24.23 (Raleigh theme)

```
Package version: 406000245
```

=== NuGet ===

Version: 3.4.3.0

=== Xamarin.Profiler ===

Version: 0.34.0
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 8.0 (11246)
Build 8A218a

=== Xamarin.iOS ===

Version: 10.0.0.6 (Xamarin Enterprise)
Hash: 6c3fee4
Branch: xcode8
Build date: 2016-09-09 13:01:32-0400

=== Xamarin.Mac ===

Not Installed

=== Xamarin.Android ===

Version: 7.0.0.18 (Xamarin Enterprise)
Android SDK: /Users/[]/Library/Developer/Xamarin/android-sdk-mac_x86
    Supported Android versions:
        2.3    (API level 10)
        4.0.3  (API level 15)
        4.1    (API level 16)
        4.2    (API level 17)
        4.3    (API level 18)
        4.4    (API level 19)
        4.4.87 (API level 20)
        5.0    (API level 21)
        5.1    (API level 22)
        6.0    (API level 23)
        7.0    (API level 24)

SDK Tools Version: 25.2.2
SDK Platform Tools Version: 24.0.2
SDK Build Tools Version: 24.0.2

Java SDK: /usr
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Android Player ===

Version: 0.6.5
Location: /Applications/Xamarin Android Player.app

=== Build Information ===

Release ID: 601005441
Git revision: 68292d1ab289911c815ddc715dd7cc29a9752f9f
Build date: 2016-09-09 04:43:23-04
Xamarin addins: ed25d008672663eeb9db55f1ccecb3c24d2fd3b2
Build lane: monodevelop-lion-cycle8

=== Operating System ===

Mac OS X 10.11.6
Darwin []-iMac.local 15.6.0 Darwin Kernel Version 15.6.0
    Mon Aug 29 20:21:34 PDT 2016
    root:xnu-3248.60.11~1/RELEASE_X86_64 x86_64

=== Enabled user installed addins ===

Macaque Tips 0.1.1

**Comment by jamesmontemagno** [comment]
Have you tried to uninstall all of the xamarin.android and mono runtimes on the emulator devices in settings/apps and scroll through to find them and then it would deploy a new version of it?

**Comment by ronpf** [comment]
Just tried that on a API 23 emulator and got same error as before.

**Comment by wierzba3** [comment]
I'm experiencing the same issue and that fix did not work for me too

**Comment by jamesmontemagno** [comment]
Perhaps give your Application class a name in the [Application] attribute and see if that works.

**Comment by jamesmontemagno** [comment]
Seems like more of a Xamarin.Android bug then with the library as it is just a subclass of the application class.

**Comment by wierzba3** [comment]
What name should it have?

**Comment by wierzba3** [comment]
And you are correct my google search pointed me to this issue, I'm not using this plugin at all. Apologies

**Comment by Emmarex** [comment]
I am having this same issue.. My app works fine on on Android 5.0 and above but it crashes on anything below Android 5.0. please help.

**Comment by zanesc** [comment]
Seeing this same issue @Emmarex . Just started yesterday i believe.

**Comment by Emmarex** [comment]
Please is there any fix for this? Am currently working on a project ....

**Comment by zanesc** [comment]
I have seen the turning off "Use Shared Mono Runtime" fixed this issue in the past but it does not work for me currently.

**Comment by zanesc** [comment]
@Emmarex I have found the solution! It is a known bug in the Xamarin 15.3 release. Here is all the info that you need as well as the links for more info.

> 59036 [Xamarin.Android] – ClassNotFoundException when building and running app with Multi-Dex enabled due to missing newline characters in generated multidex.keep file.
Possible temporary workaround: Copy the generated multidex.keep file from the obj directory into the top level of the Android app project, add a newline character after each “.class” string, set the build action of the file to MultiDexMainDexList, and rebuild the app.

https://releases.xamarin.com/stable-release-15-3-4-servicing-release/
https://bugzilla.xamarin.com/show_bug.cgi?id=59036

**Comment by Emmarex** [comment]
Thanks @zanesc

**Comment by Emmarex** [comment]
This solves the issue.

https://www.jimbobbennett.io/fixing-issues-with-multidex-on-pre-lollipop-devices-on-windows/
