### ISSUE TITLE
Is there a version of this plugin that is compatible with .NET Standard Lib?

### ISSUE THREAD

**Issue by xinunix** [jamesmontemagno/CurrentActivityPlugin#11]
Looks like we can't add this plugin to a .NET Standard Lib, only pcl.  Some of the other plugins like Geolocator & Permissions (which I thought were using CurrentActivity) appear to have been updated to support .NET Standard but when I try to add CurrentActivity it tells me it isn't compatible.

**Comment by jamesmontemagno** [comment]
This can only be installed in Android and is not for anything else.
