### ISSUE TITLE
Not Compatible with netstandard 2.0

### ISSUE THREAD

**Issue by BillyMartin1964** [jamesmontemagno/CurrentActivityPlugin#16]
Plugin.CurrentActivity 2.0.0.6-beta is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package Plugin.CurrentActivity 2.0.0.6-beta supports: monoandroid44 (MonoAndroid,Version=v4.4)

**Comment by jamesmontemagno** [comment]
It is only for Android projects, it isn't for .NET Standard or PCL projects.
