### ISSUE TITLE
NuGet Package Target Xamarin.iOS Version 1.0 issues

### ISSUE THREAD

**Issue by hvaughan3** [jamesmontemagno/CurrentActivityPlugin#2]
Please fill out either the bug or feature request section and remove whatever section you are not using.

## Bug 

Version Number of Plugin: 1.0.1
Xamarin Forms Version: 2.3.0.107

### Expected Behavior
Plugin installs successfully into brand new project.

### Actual Behavior
Receive error upon attempting to install the plugin into a Forms project:

> Could not install package 'Plugin.CurrentActivity 1.0.1'. You are trying to install this package into a project that targets 'Xamarin.iOS,Version=v1.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

### Steps to reproduce the Behavior
Create brand new Xamarin Form PCL project using Visual Studio 2015.
Updated Xamarin Forms library to version 2.3.0.107.
Attempt to install Current Activity Plugin into Forms, Android, and iOS projects.

### Troubleshooting Steps
Attempted to delete all `/bin/` and `/obj/` directories.

Attempted to only target (and different combinations of below):
 **.NET Framework 4.5.1**
 **Windows8.1**
 **Xamarin.Android**
 **Xamarin.iOS**
 **Xamarin.iOS (Classic)**

The strange thing to me is that I have an older project that this plugin works just fine with. Although with that one Current Activity was installed as a dependency of your Permissions plugin. Thanks so much for all your help and all of your contributions to the community.

**Comment by hvaughan3** [comment]
Installing Current Activity directly into the Xamarin Android project worked just fine.

**Comment by jamesmontemagno** [comment]
This package only support Android as it has to do with Android activities.It is only a dependency on Android specific plugins.
