### ISSUE TITLE
Error updating plugin to version 2.0.1.4 with VS 15.7.0

### ISSUE THREAD

**Issue by ozzy1873** [jamesmontemagno/CurrentActivityPlugin#20]
After upgrading to VS 15.7.0 I am getting the following error when trying to update the plugin from version 1.01 to version 2.0.1.4. I don't know if this is truly a bug in the plugin or something caused by Visual Studio:

Failed to add reference. The package 'Plugin.CurrentActivity' tried to add a framework reference to 'System.Collections' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.

Version of Xamarin: 2.5.1.527436

**Comment by jamesmontemagno** [comment]
Are you just trying to add it to your Android project?

**Comment by ozzy1873** [comment]
More info:
I updated NETStandard.Library from 2.0.1 to 2.0.3 and now instead of System.Collections not found in the GAC, it's System.Runtime.

**Comment by ozzy1873** [comment]
Got it working. I manually added this to the Adroid csproj file:
<Reference Include="System.Runtime"/>

**Comment by ozzy1873** [comment]
Thanks! I rolled back to 1.0.1 and then updated to 2.1.0.1 with no issues. BTW, I had the same problem with the Settings plugin.

**Comment by jamesmontemagno** [comment]
awesome :) yeah, there was some weird packaging issue :( however we fixed it up now with 2.1.0.1 and I am rolling out updates to all plugins using new SDK style tooling this week :)

**Comment by MagnusJohansson** [comment]
I am still getting this error with the 2.1.0.1:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Failed to add reference. The package 'Plugin.CurrentActivity' tried to add a framework reference to 'System.Runtime' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.
Error HRESULT E_FAIL has been returned from a call to a COM component.			0	
```

**Comment by jamesmontemagno** [comment]
See above of move to reference packages.

**Comment by HoGo72** [comment]
Thanks, I could install now 2.1.0.2 without any problem

**Comment by jamesmontemagno** [comment]
:)
