### ISSUE TITLE
Getting System.MissingMethodException

### ISSUE THREAD

**Issue by jerriep** [jamesmontemagno/CurrentActivityPlugin#21]
## Bug Information

Version Number of Plugin: 2.1.0.2
Device Tested On: -
Simulator Tested On: Android_Accelerated_Nougat
Version of VS:  Visual Studio for Mac 7.5
Version of Xamarin: Xamarin.Android Version: 8.3.0.19
Versions of other things you are using:

### Steps to reproduce the Behavior

I updated from the 1.x version of the Plugin to 2.x. I created the following MainApplication class

    [Application]
    public class MainApplication : Application
    {
        public MainApplication(IntPtr handle, JniHandleOwnership transer)
          : base(handle, transer)
        {
        }

        public override void OnCreate()
        {
            base.OnCreate();
            CrossCurrentActivity.Current.Init(this);
        }
    }

When my application launches I get the following exception:

```
System.MissingMethodException: void Plugin.CurrentActivity.ICurrentActivity.Init(Android.App.Application)
```

Not sure where it originates, as I cannot see a stack trace...

### Expected Behavior

No exception?

**Comment by jamesmontemagno** [comment]
What if you put it in your main activity and to Init(this, bundle) ?

Could be just a nuget caching issue.

**Comment by juanrobertodeanda** [comment]
I updated to Xamarin Forms 3 and now everything is working.

**Comment by jamesmontemagno** [comment]
Most likely just a nuget cache issue.

I created a new project and didn't have any issues.
[App2.zip](https://github.com/jamesmontemagno/CurrentActivityPlugin/files/2014208/App2.zip)


Delete the bin/obj.

**Comment by jerriep** [comment]
Deleted the bin and obj folders sorted this out for me, thanks!

**Comment by deepakyogi1995** [comment]
Hello @jamesmontemagno ,

I am getting System.MissingMethodException: void Plugin.CurrentActivity.ICurrentActivity.Init(Android.App.Application).

XF : 3.1.0.697729
Plugin.CurrentActivity :  2.1.0.2

I tried upaded Plugin.CurrentActivity plugin but not solve.


 public class MainApplication : Application
    {
        public MainApplication(IntPtr handle, JniHandleOwnership transer)
          : base(handle, transer)
        {
        }

        public override void OnCreate()
        {
            base.OnCreate();
            CrossCurrentActivity.Current.Init(this);
        }
    }


Use this in main activity

 CrossCurrentActivity.Current.Init(this, bundle);

Any solution
