### ISSUE TITLE
Nuget info points to monodroidtoolkit

### ISSUE THREAD

**Issue by matthews-jca** [jamesmontemagno/CurrentActivityPlugin#23]
## Bug Information

Version Number of Plugin: 2.1.0.2
Device Tested On: VS2017
Simulator Tested On:
Version of VS: 15.7.1
Version of Xamarin: NA
Versions of other things you are using: NA

### Steps to reproduce the Behavior

View nuget package information

### Expected Behavior

Project URL point to this repo

### Actual Behavior

Project URL and license point to MonoDroidToolkit

### Screenshotst

![image](https://user-images.githubusercontent.com/19495639/40244237-f57d52d2-5a87-11e8-8894-7e79b22c981e.png)

**Comment by jamesmontemagno** [comment]
cleaned it up :) thanks
