### ISSUE TITLE
Plugin.CurrentActivity 2.1.0.2 not compatible to netstandard2.0

### ISSUE THREAD

**Issue by jbohrmann** [jamesmontemagno/CurrentActivityPlugin#24]
Hello,

I tried to install/use Plugin.Permissions which needs Plugin.CurrentActivity.
I was not able to install Plugin.CurrentActivity as my Project is .NET Standard.

## Bug Information

Version Number of Plugin: 2.1.0.2
Device Tested On: Samsung Galaxy S8
Simulator Tested On:
Version of VS: 2017 15.7.2
Version of Xamarin: v4 Android 27.0.2
Versions of other things you are using: .NET Standard v2.0

### Steps to reproduce the Behavior
- New .Net Standard Project
- Manage Nuget Packages
- Try to install Plugin.CurrentActivity

### Expected Behavior
Install plugin.

### Actual Behavior
Not able to install Plugin.

### Code snippet
No code so far.

### Screenshotst
German error message when trying to install plugin.

**Comment by jamesmontemagno** [comment]
You only need it in the Android project and need to init there.
