### ISSUE TITLE
The package 'Plugin.CurrentActivity' tried to add a framework reference to 'Java.Interop' which was not found in the GAC

### ISSUE THREAD

**Issue by nguyenthanhliemfc** [jamesmontemagno/CurrentActivityPlugin#26]
**Severity	Code	Description	Project	File	Line	Suppression State
Error		Failed to add reference. The package 'Plugin.CurrentActivity' tried to add a framework reference to 'Java.Interop' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.
Reference unavailable.**			0	

If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin:
Device Tested On:
Simulator Tested On:
Version of VS: 2017.7.3
Version of Xamarin: 3.0.0.5
Versions of other things you are using:

**Comment by jamesmontemagno** [comment]
Interesting, Haven't seen this before. Can you just try to add the reference manually. Seems like perhaps just an old csproj issue.
