### ISSUE TITLE
Could not find android.jar for API Level 19 when compiling

### ISSUE THREAD

**Issue by hroblesm** [jamesmontemagno/CurrentActivityPlugin#28]
Hi,

I just opened the solution with VS2017 and get the following error when compiling:

Error	XA5207	Could not find android.jar for API Level 19. This means the Android SDK platform for API Level 19 is not installed. Either install it in the Android SDK Manager (Tools > Open Android SDK Manager...), or change your Xamarin.Android project to target an API version that is installed. (C:\Program Files (x86)\Android\android-sdk\platforms\android-19\android.jar missing.)	Plugin.CurrentActivity.Android

**Comment by jamesmontemagno** [comment]
Either install it in the Android SDK Manager (Tools > Open Android SDK Manager...), or change your Xamarin.Android project to target an API version that is installed.

**Comment by hroblesm** [comment]
Hi James,

The question is why the VS is looking for the Android API level 19. I have changed the API version to the 
CurrentActivityTest to 21 but still getting the error. And for the Plugin.CurrentActivity.Android there is not option to change it.

<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="CurrentActivityTest.CurrentActivityTest" android:versionCode="1" android:versionName="1.0" android:installLocation="auto">
	<uses-sdk android:minSdkVersion="21" />
	<application android:label="CurrentActivityTest"></application>
</manifest>

**Comment by jamesmontemagno** [comment]
My recommendation is to just install the API 19 from the SDK Manager.

The library project you will find it <TargetFramework>MonoAndroid44</TargetFramework>
