### ISSUE TITLE
Please publish this plugin from a Microsoft repository

### ISSUE THREAD

**Issue by bgavrilMS** [jamesmontemagno/CurrentActivityPlugin#32]
A lot of developers use this plugin in conjunction with [MSAL](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet) - the AAD SDK.

We're starting to suggest using this plugin in our samples, and it would be better if this plugin was published by Microsoft and signed by Microsoft.

**Comment by jamesmontemagno** [comment]
Thanks for the suggestion, however this is a personal project and I don't plan on migrating anything over. We are looking into exposing this functionality in Xamarin.Essentials.
