### ISSUE TITLE
Plugin.CurrentActivity is not compatible with netstandard2.0

### ISSUE THREAD

**Issue by MRomeror** [jamesmontemagno/CurrentActivityPlugin#35]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: 2.1.0.4
Device Tested On:
Simulator Tested On:
Version of VS: for Mac 8.2.2 (build 21)
Version of Xamarin: 4.1.0.673156
Versions of other things you are using: 
Xam.Plugin.Media 4.3.1 - beta

### Steps to reproduce the Behavior
install plugin "Plugin.CurrentActivity" in PCL

### Actual Behavior
error installing
### Code snippet
Checking compatibility for Plugin.CurrentActivity 2.1.0.4 with .NETStandard,Version=v2.0.
Package Plugin.CurrentActivity 2.1.0.4 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package Plugin.CurrentActivity 2.1.0.4 supports: monoandroid44 (MonoAndroid,Version=v4.4)
### Screenshotst
![image](https://user-images.githubusercontent.com/43822946/62771978-b5d8e380-ba9e-11e9-8277-35127b7b2ac7.png)

**Comment by jamesmontemagno** [comment]
This is a library for Xamarin.Android only and only needs to be installed there.
