### ISSUE TITLE
It won't install

### ISSUE THREAD

**Issue by travelman68** [jamesmontemagno/CurrentActivityPlugin#37]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: 2.1.0.4
Device Tested On: PC
Simulator Tested On: Android Pixel Oreo Emulator
Version of VS: 2019
Version of Xamarin: FORMS: 4.1..0.555618 ESSENTIALS: 1.1.0
Versions of other things you are using:
NETStandardLibrary 2.0.3
sqllie-net-pcl 1.6.292
xam.plugin.media 4.0.1.5

### Steps to reproduce the Behavior
Using NuGet or PMC cannot install plugin

### Expected Behavior
Plugin to be installed

### Actual Behavior
Pluginn not installed

### Code snippet
No code to enter, but here is the error:
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1202	Package Plugin.CurrentActivity 2.1.0.4 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package Plugin.CurrentActivity 2.1.0.4 supports: monoandroid44 (MonoAndroid,Version=v4.4)	Contacts	

### Screenshotst
Can't get a screenshot to you

**Comment by travelman68** [comment]
If it can only be installed on Android only apps, how do I do that?

**Comment by jamesmontemagno** [comment]
Install it into you Android project
