### ISSUE TITLE
Ability to override CrossCurrentActivity.Current factory method

### ISSUE THREAD

**Issue by SlyNet** [jamesmontemagno/CurrentActivityPlugin#4]
Currently there is no way to override factory method that returns Activity. 
For example in our app we have MvvmCross and there is an existing factory `IMvxAndroidCurrentTopActivity` that we could use for geolocation plugin.

**Comment by jamesmontemagno** [comment]
It always knows the current activity so there is never ever a need for this. The activity that is returned is always the top activity.
