### ISSUE TITLE
Does Xamarin.Essentials Platform Extensions replace this Plugin?

### ISSUE THREAD

**Issue by jthegeman** [jamesmontemagno/CurrentActivityPlugin#41]
Does the Xamarin.Essentials: Platform Extensions replace this Plugin or is there a need for both, or reason to chose one of the other?

**Comment by jamesmontemagno** [comment]
Yes, that is the idea :)

**Comment by jthegeman** [comment]
Thank you! What is the best way to reach you, I had a couple of other questions, I tried using twitter.

**Comment by EmilAlipiev** [comment]
hi @jamesmontemagno, according to https://github.com/jamesmontemagno/CurrentActivityPlugin/blob/6458fd91e83c6b56bbfda2c80b5cefcdbae2fe0a/nuget/readme.txt

you suggest to set current.activity as below in the application class but Xamarin.essentials has it readonly. Do you know how can we handle this?

```
 public void OnActivityStarted(Activity activity)
        {
            CrossCurrentActivity.Current.Activity = activity;
        }
```
