### ISSUE TITLE
Unable to use InAppBillingPlugin because CrossCurrentActivity.Current.Activity returns null

### ISSUE THREAD

**Issue by CrewNerd** [jamesmontemagno/CurrentActivityPlugin#42]
## Bug Information

Version Number of Plugin: 2.1.0.4
Device Tested On: Samsung Galaxy S5
Simulator Tested On:
Version of VS: 16.7.3
Version of Xamarin: 16.7.000.440 (Android Xamarin SDK 11.0.2.0)

Versions of other things you are using:
InAppBillingPlugin: 4.0.0-beta
Latest version of various Xamarin.AndroidX components
NETStandard.Library 2.0.3

### Steps to reproduce the Behavior

I've tried all combinations of initializing the CurrentActivityPlugin in the Application & MainActivity.
I also tried the last solution recommended here: https://stackoverflow.com/questions/50533928/crosscurrentactivity-current-activity-is-null-despite-initializing-and-setting

### Expected Behavior

CrossCurrentActivity.Activity returns non-null value, and InAppBillingPlugin doesn't throw an exception.

### Actual Behavior

I can connect with the InAppBillingPlugin and enumerate a set of consumable products, but when I attempt a purchase, an exception is throw with the message:
"Current Activity is null, ensure that the MainActivity.cs file is configuring Xamarin.Essentials in your source code so the In App Billing can use it."

A subscription purchase is also failing, but doesn't throw this exception, so that could be an unrelated issue.

### Code snippet

    public class CrewNerdApp : Application, Application.IActivityLifecycleCallbacks
    {
        public override void OnCreate()
        {
            base.OnCreate();

            RegisterActivityLifecycleCallbacks(this);

            CrossCurrentActivity.Current.Init(this);
            AppCenter.Start(AppCenterAppId, typeof(Analytics), typeof(Crashes), typeof(Distribute));
            Analytics.SetEnabledAsync(true).ContinueWith((_) => Analytics.TrackEvent("AppLaunch"));
        }

**Comment by jamesmontemagno** [comment]
4.0 doesn't use this add int.

Ensure you initialize Xamarin.Essentials in your Android app.

**Comment by CrewNerd** [comment]
Thanks for the quick response - trying that now.

**Comment by jamesmontemagno** [comment]
see https://github.com/jamesmontemagno/inappbillingplugin#version-4-major-update---android

**Comment by CrewNerd** [comment]
Thanks - I'm getting farther now.
