### ISSUE TITLE
MainApplication with manifest file

### ISSUE THREAD

**Issue by biozal** [jamesmontemagno/CurrentActivityPlugin#7]
## Bug Information

Version Number of Plugin:  1.0.1
Device Tested On:  Several (Note 5, Note 8, Edge 6, Pixel, Pixel 2)
Simulator Tested On:  
Version of VS:  2017 15.4
Version of Xamarin:  Latest (8.0.0.33)
Versions of other things you are using:  Compiler set to API 25

### Steps to reproduce the Behavior
Trying to build an application using this.  Our application has several other things in it that require among other things access to the file system.   Because of this we need the manifest file to have an entry for application with XML like this:  

	<application android:allowBackup="true" android:label="@string/app_name" android:theme="@style/AppTheme" android:largeHeap="true">
		<meta-data android:name="com.google.android.maps.v2.API_KEY" android:value="@string/google_maps_key" />
	<provider android:name="android.support.v4.content.FileProvider" 
          android:authorities="com.xx.fileprovider" 
          android:exported="false" 
          android:grantUriPermissions="true">
            <meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/file_paths"></meta-data>
        </provider>
	</application>

Because of this - it conflicts with the [Application] attribute on the "MainApplication" class.  We tried to then put the name: element on the application node in the manifest.xml but according to the Xamarin SDK that's not supported (there is a TODO item on it).  So we can't tell the manifest which application to call on start up.  We tried then taking all the manifest application attributes and putting it on the MainApplication class - but we can't figure out how to do the provider for file permissions as an attribute on the MainApplication class.  When we compile the application we get an error.  See Actual Behavior section for compiler error.

### Expected Behavior
We should be able to use the FileProvider along with the MainApplication class.

### Actual Behavior
Compiler error:
Error MSB4018: The "GenerateJavaStubs" task failed unexpectedly.
System.InvalidOperationException: Application cannot have both a type with an [Application] attribute and an [assembly:Application] attribute.

### Code snippet
The XML from our manifest file is up in the steps to reproduce section.  OurApplication class is the stock class below:

MainApplication.cs
    //You can specify additional application information in this attribute
    [Application]
    public class MainApplication : Application, Application.IActivityLifecycleCallbacks

### Screenshotst
N/A

**Comment by jamesmontemagno** [comment]
This is not the issue. the issue is because you have [assembly:Application] somewhere in your app. Search for it, it is probably in your Properties.cs

**Comment by biozal** [comment]
@jamesmontemagno - this isn't the issue.  It's NO WHERE in the app.  Here is my AssemblyInfo.cs in our app:

using System.Reflection;

// Information about this assembly is defined by the following attributes. 
// Change them to the values specific to your project.

[assembly: AssemblyTitle("xxx.xxx.xxx")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("")]
[assembly: AssemblyProduct("")]
[assembly: AssemblyCopyright("(c) Aaron LaBeau")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

// The assembly version has the format "{Major}.{Minor}.{Build}.{Revision}".
// The form "{Major}.{Minor}.*" will automatically update the build and revision,
// and "{Major}.{Minor}.{Build}.*" will update just the revision.

[assembly: AssemblyVersion("1.0.0")]

// The following attributes are used to specify the signing key for the assembly, 
// if desired. See the Mono documentation for more information about signing.

//[assembly: AssemblyDelaySign(false)]
//[assembly: AssemblyKeyFile("")]

On top of this - I did a grep of the word Application and looked at EVERY single file using:  

grep -Hnr "Application" *

The only remote thing I saw that had the word Application in it that I didn't write or wasn't in a ginary file was this auto generated designer file:
Resources/Resource.designer.cs:12:[assembly: global::Android.Runtime.ResourceDesignerAttribute("EY.Connect.UI.Droid.Resource", IsApplication=true)]

**Comment by jamesmontemagno** [comment]
Having the application node in the androidmanifest and the custom class is absolutely perfect and I have been doing so for 6 years in 70+ apps.

You can check the sample here: https://github.com/jamesmontemagno/MediaPlugin/tree/master/samples

That uses this exact setup. You can send me your project and I can take a look: motz@microsoft.com if you can't post it.

**Comment by biozal** [comment]
Dude - totally agree with you and I have other apps that I've made custom applications options with without problems - I have an example from two years ago that I did to prove you could setup MvvmCross without needing the splash screen.  I'm just trying to figure out why now it's happening.  I just need to manually get the compiler out and do a verbose out to see what it's really complaining about.

**Comment by jamesmontemagno** [comment]
If you have the sample that is causing issues just send it my way and I can figure out what is goign on.
